const fs = require('fs');
const path = require('path');

// Define directories to create
const dirs = [
  'src/actions',
  'src/app/add',
  'src/app/history',
  'src/app/budget',
  'src/components/ui',
  'src/lib',
  'src/types',
  'public'
];

// Define files to create (skips files already generated by Next.js like layout.tsx)
const files = [
  'src/actions/transactions.ts',
  'src/app/add/page.tsx',
  'src/app/history/page.tsx',
  'src/app/budget/page.tsx',
  'src/components/BottomNav.tsx',
  'src/components/TransactionForm.tsx',
  'src/components/SummaryCard.tsx',
  'src/lib/supabase.ts',
  'src/lib/utils.ts',
  'src/types/index.ts',
  'public/manifest.json',
  '.env.local'
];

// Create directories
dirs.forEach(dir => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`📁 Created directory: ${dir}`);
  }
});

// Create empty files
files.forEach(file => {
  if (!fs.existsSync(file)) {
    fs.writeFileSync(file, '// Ready for code\n');
    console.log(`📄 Created file: ${file}`);
  } else {
    console.log(`⏭️  Skipped existing file: ${file}`);
  }
});

console.log('✅ Project structure created successfully!');